import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Bottomnavbar from "../components/component/Navbar";
import { Navbar } from "@nextui-org/react";
import { ThemeProvider } from "@/components/component/theme-provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body className="">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>{children}</Providers>
          <Bottomnavbar />
        </ThemeProvider>
      </body>
    </html>
  );
}
