import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Bottomnavbar from "../components/component/Navbar";
import { Navbar } from "@nextui-org/react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="max-w-sm mx-auto">
        <Providers>{children}</Providers>
        <Bottomnavbar />
      </body>
    </html>
  );
}
